kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-configmap-168
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.24.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "Sample 1",
            "remark": "Simple HTTP application with RR pool",
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "configmap-168": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.169.72.168"
                        ],
                        "remark":"ingress: f5demo",
                        "virtualPort": 80,
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
